# Generated by Django 2.2 on 2019-04-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=200)),
            ],
        ),
    ]
