# Generated by Django 2.1.7 on 2019-04-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
    ]
